### ISSUE TITLE
Implement all test types

### ISSUE THREAD

**Issue by apeace** [apeace/devicefarm#12]
List of test types is here: http://docs.aws.amazon.com/devicefarm/latest/developerguide/test-types-intro.html

**Android**
- [ ] Appium Java Junit
- [ ] Appium Java TestNG
- [ ] Appium Python
- [ ] Calabash
- [x] Instrumentation
- [ ] UI Automator

**iOS**
- [ ] Appium Java Junit
- [ ] Appium Java TestNG
- [ ] Appium Python
- [ ] Calabash
- [ ] UI Automation
- [ ] XCTest
- [ ] XCTest UI

**Web Apps**
- [ ] Appium Java Junit
- [ ] Appium Java TestNG
- [ ] Appium Python

Config could look something like:

``` yaml
defaults:
  tests:
    my_instrumentation:
      type: android_instrumentation
      app: ./path/to/build.apk
      test: ./path/to/instrumentation.apk
    my_appium:
      type: android_appium_python
      app: ./path/to/build.apk
      test: ./path/to/appium-python.zip
```

**Not** in scope for this ticket: builtin Explorer/Fuzz tests.
